// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "iPhone (111)"
#define SECRET_PASS "km0218**"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "a1yxvsjof87e7l-ats.iot.ap-northeast-2.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICiDCCAXCgAwIBAgIUUiBe7NuDk/d5Uy7zSoKk+/gRfFEwDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIyMTIwNDEwMDcy
NFoXDTQ5MTIzMTIzNTk1OVowGDEWMBQGA1UEAxMNTXlNS1JXaUZpMTAxMDBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABNiIozL12/9vwiBDbTzQIcxfw75lhPqzmfzg
xqyFvG4bZqaBcFknyjMD5OCg/4Bor1gSkxxE4NFOd5OIRduINY2jYDBeMB8GA1Ud
IwQYMBaAFNbiLIBD/YtnKU7SihV/xSk5zH0+MB0GA1UdDgQWBBTy3lGtVGuIhqjO
w04KuSNqqaedrjAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG
9w0BAQsFAAOCAQEAJm/6xyNoZR/NrvDbFWHo1sjVCTxCM0oJPhKTKKeSJVhNFeuk
hSX/U6HthwrmuGe9R8PQuNBbQv+J6tW1VoVR1RL1YDUqPUlCsKIjtui5XIkq/p9B
ye8zNi1l6QoM2RqBNgovbL8IBlEyko/vnFhmrVdoJlG6Bm2KKt8hPvG9R8z6J0qd
v/8YoMZgDGFjIHPcewRfz2ZMrmFCIIciyWsaDNUl9giI4yfEZViMWuGPYoEOIxrB
qa5ydjU72Q5yjzZNbtxlokmmQhl/tSa8uHkFGDeC6WViAUfvt0ZmaB6gQA62loAj
SAUQi9LjVOgw6pf/KkiZCext8oD3i24lAZV7KA==
-----END CERTIFICATE-----
)";
